server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl auto: update
  application:
    name: bookprojectt
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin





